import _Dashboard from './Dashboard.jsx';
import _Orders from './Orders.jsx';
import _Documents from './Documents.jsx';
import _Sales from './Sales.jsx';
import _Materials from './Materials.jsx';
import _Contacts from './Contacts.jsx';
import _Promotion from './Promotion.jsx';
import _Profile from './Profile.jsx';
import _Marketing from './Marketing.jsx';
import _Bills from './Bills.jsx';
import _Notifications from './Notifications.jsx';
import _Chat from './Chat.jsx';
import _Question from './Question.jsx';
import _Mailer from './Mailer.jsx';
import _Login from './Login.jsx';
import _EditOrder from './EditOrder.jsx';
import _EditContact from './EditContact.jsx';

export const Dashboard = _Dashboard;
export const Orders = _Orders;
export const Documents = _Documents;
export const Sales = _Sales;
export const Materials = _Materials;
export const Contacts = _Contacts;
export const Promotion = _Promotion;
export const Profile = _Profile;
export const Marketing = _Marketing;
export const Bills = _Bills;
export const Notifications = _Notifications;
export const Chat = _Chat;
export const Question = _Question;
export const Mailer = _Mailer;
export const Login = _Login;
export const EditOrder = _EditOrder;
export const EditContact = _EditContact;
